#!/bin/bash

echo """
  ____  _                         _   _
 / ___|| |_ _____   _____ _ __   | | | | ___  _ __ _ __  _   _ _ __   __ _
 \___ \| __/ _ \ \ / / _ \ '_ \  | |_| |/ _ \| '__| '_ \| | | | '_ \ / _\` |
  ___) | |_  __/\ V /  __/ | | | |  _  | (_) | |  | | | | |_| | | | | (_| |
 |____/ \__\___| \_/ \___|_| |_| |_| |_|\___/|_|  |_| |_|\__,_|_| |_|\__, |
                                                                     |___/
"""

if [ -n "$2" ]; then
  VELOCITY=0 ROOT_URL=$2 meteor run $1 --settings private/settings.json --mobile-server $2
else
  VELOCITY=0 meteor run $1 --settings private/settings.json
fi